/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LagzDesign (https://sketchfab.com/LagzDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-setup-v2-low-poly-c4aafe2ed67841b9b52e80e8e469dbb8
Title: gaming setup v2 (low-poly)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Computer3 =(props) => {
  const { nodes, materials } = useGLTF('/pc_3/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="gaming_setupfbx" scale={0.01}>
        <group name="desk" rotation={[2e-7, 0, 0]} scale={100}>
          <mesh
            name="desk_Material002_0"
            castShadow
            receiveShadow
            geometry={nodes.desk_Material002_0.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="desk_Material001_0"
            castShadow
            receiveShadow
            geometry={nodes.desk_Material001_0.geometry}
            material={materials['Material.001']}
          />
        </group>
        <group
          name="Plane006"
          position={[-80.3678131, 411.6998291, -6.1692038]}
          rotation={[2e-7, 0, 0.0098223]}
          scale={83.7014694}>
          <mesh
            name="Plane006_Material009_0"
            castShadow
            receiveShadow
            geometry={nodes.Plane006_Material009_0.geometry}
            material={materials['Material.009']}
          />
          <mesh
            name="Plane006_Material010_0"
            castShadow
            receiveShadow
            geometry={nodes.Plane006_Material010_0.geometry}
            material={materials['Material.010']}
          />
        </group>
        <group
          name="Cylinder"
          position={[32.2514572, 408.2087097, 356.4216614]}
          rotation={[-Math.PI / 2, -0.019607, 0.5093839]}
          scale={[148.0444489, 148.0444336, 148.0444489]}>
          <mesh
            name="Cylinder_plastic002_0"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_plastic002_0.geometry}
            material={materials['plastic.002']}
          />
          <mesh
            name="Cylinder_screen002_0"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_screen002_0.geometry}
            material={materials['screen.002']}
          />
        </group>
        <group
          name="Plane_Plane001"
          position={[0, 362.1929321, -239.5490112]}
          rotation={[2e-7, 0, 0]}
          scale={100}>
          <mesh
            name="Plane_Plane001_Material011_0"
            castShadow
            receiveShadow
            geometry={nodes.Plane_Plane001_Material011_0.geometry}
            material={materials['Material.011']}
          />
          <mesh
            name="Plane_Plane001_Material018_0"
            castShadow
            receiveShadow
            geometry={nodes.Plane_Plane001_Material018_0.geometry}
            material={materials['Material.018']}
          />
          <mesh
            name="Plane_Plane001_Material019_0"
            castShadow
            receiveShadow
            geometry={nodes.Plane_Plane001_Material019_0.geometry}
            material={materials['Material.019']}
          />
          <mesh
            name="Plane_Plane001_Material020_0"
            castShadow
            receiveShadow
            geometry={nodes.Plane_Plane001_Material020_0.geometry}
            material={materials['Material.020']}
          />
        </group>
        <primitive object={nodes._rootJoint} />
        <primitive object={nodes._rootJoint_1} />
        <group
          name="whole_boundary_Plane004"
          position={[294.7674255, 0, -77.8738098]}
          rotation={[2e-7, -0.6657898, 1e-7]}
          scale={[31.6343193, 31.6343155, 31.6343193]}>
          <mesh
            name="whole_boundary_Plane004_plastic_0"
            castShadow
            receiveShadow
            geometry={nodes.whole_boundary_Plane004_plastic_0.geometry}
            material={materials.plastic}
          />
          <mesh
            name="whole_boundary_Plane004_chair_material_0"
            castShadow
            receiveShadow
            geometry={nodes.whole_boundary_Plane004_chair_material_0.geometry}
            material={materials.chair_material}
          />
          <mesh
            name="whole_boundary_Plane004__white_metal_0"
            castShadow
            receiveShadow
            geometry={nodes.whole_boundary_Plane004__white_metal_0.geometry}
            material={materials.white_metal}
          />
          <mesh
            name="whole_boundary_Plane004_black_metal_0"
            castShadow
            receiveShadow
            geometry={nodes.whole_boundary_Plane004_black_metal_0.geometry}
            material={materials.black_metal}
          />
        </group>
        <mesh
          name="pad_Material_0"
          castShadow
          receiveShadow
          geometry={nodes.pad_Material_0.geometry}
          material={materials.Material}
          position={[45.7221298, 259.5209961, 6.4876838]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[72.6714706, 201.1430054, 100]}
        />
        <mesh
          name="Plane_Material003_0"
          castShadow
          receiveShadow
          geometry={nodes.Plane_Material003_0.geometry}
          material={materials['Material.003']}
          position={[53.3244896, 259.1914063, 52.8403053]}
          rotation={[Math.PI, 1.5093707, -Math.PI]}
          scale={28.7804222}
        />
        <mesh
          name="Plane002_Material004_0"
          castShadow
          receiveShadow
          geometry={nodes.Plane002_Material004_0.geometry}
          material={materials['Material.004']}
          position={[57.1505623, 259.5140381, -108.0997009]}
          rotation={[0.0000026, 1.5072206, -0.0000026]}
          scale={[24.0709648, 26.5339012, 24.0709648]}
        />
        <mesh
          name="Plane001_Material005_0"
          castShadow
          receiveShadow
          geometry={nodes.Plane001_Material005_0.geometry}
          material={materials['Material.005']}
          position={[-87.9471207, 258.7881165, 167.1338654]}
          rotation={[2e-7, 0.2752374, 0]}
          scale={29.2046394}
        />
        <mesh
          name="Plane003_Material005_0"
          castShadow
          receiveShadow
          geometry={nodes.Plane003_Material005_0.geometry}
          material={materials['Material.005']}
          position={[-86.3720016, 258.7881165, -192.7804108]}
          rotation={[2e-7, -0.2649487, 0]}
          scale={[29.2046375, 29.2046394, 29.2046375]}
        />
        <mesh
          name="Cube_Material014_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material014_0.geometry}
          material={materials['Material.014']}
          position={[-143.5652008, 251.3950348, 144.5633545]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[14.839922, 14.839922, 10.2306929]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/pc_3/scene.gltf')

export default Computer3;
