/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DioneBegoode (https://sketchfab.com/DioneBegoode)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-high-tech-computer-lowpoly-036a7fd5f6f84e72bf836ace9fc81c79
Title: Sci Fi High Tech Computer Lowpoly
*/

import React, { useRef } from "react";
import { useGLTF, useVideoTexture } from "@react-three/drei";
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';

const DemoComputer = (props) => {
  const { nodes, materials } = useGLTF("/holographic_demo/scene.gltf");
  const group = useRef();

  const txt = useVideoTexture(
    props.texture ? props.texture : "/textures/project/project1.mp4"
  );

  useGSAP(() => {
    gsap.from(group.current.rotation, {
      y: Math.PI / 2,
      duration: 1,
      ease: 'power3.out',
    });
  }, [txt]);

  return (
    <group {...props} ref={group} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials["Material.012"]}
        position={[0.37406, 0.02742, -2.75561]}
        rotation={[0, 0, -0.23725]}
        scale={[0.36648, 0.41844, 0.68851]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials["Material.013"]}
        position={[0.00955, 0.67447, -2.75517]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.43553, 0.93013, 1.0258]}
      >
        <meshBasicMaterial map={txt} toneMapped={false} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials["Material.014"]}
        position={[0.02643, -0.01393, -2.75485]}
        rotation={[0, 0, -0.24381]}
        scale={0.85793}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials["Material.014"]}
        position={[0.34565, -0.18212, -2.75095]}
        rotation={[0, 0, -0.14477]}
        scale={0.85793}
      />
    </group>
  );
};

useGLTF.preload("/holographic_demo/scene.gltf");

export default DemoComputer;
