/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Fred Drabble (https://sketchfab.com/FredDrabble)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/picture-frame-1520-dimensions-2a75286422e64948b1d6626bc9c6d47d
Title: PICTURE FRAME 15*20 dimensions
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useLoader } from "@react-three/fiber";

const Frame = (props) => {
  const { nodes, materials } = useGLTF("/frame_gold/scene.gltf");
  const texture1 = useLoader(THREE.TextureLoader, "/textures/Scrum2.png");

  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.12721, 0, 0]}>
        <group rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.03}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.painting_aiStandardSurface1_0.geometry}
            position={[0, -0.88419, 0]}
            rotation={[0, -Math.PI / 2,0 ]} // Rotate the image by 90 degrees
            scale={[2, 0.3, 1]} 
          >
            <meshBasicMaterial map={texture1} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.frame_lambert1_0.geometry}
            material={materials.lambert1}
            position={[0, 0.86024, 0]}
            scale={[0.94171, 0.89025, 0.94171]}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/frame_gold/scene.gltf");
export default Frame;
