/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tyron (https://sketchfab.com/Omty)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/antique-table-f01054c29829452a9f87437de57a3f6f
Title: Antique Table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import * as THREE from 'three'

const Table = (props) => {
  const { nodes, materials } = useGLTF('/table/scene.gltf')
  const woodTexture = useLoader(THREE.TextureLoader, '/textures/gold.jpg')

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.defaultMat}
        >

        </mesh>

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.defaultMat}
        >
                        <meshBasicMaterial map={woodTexture} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/table/scene.gltf')
export default Table